name: Build and deploy
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Actions/checkout
        uses: actions/checkout@v2.3.4
      - name: Actions/setup-node
        uses: actions/setup-node@v2.1.2
      - name: NPM install
        uses: jaid/action-npm-install@v1.2.1
      - name: NPM build
        run: npm run build
